sudo: false
language: haskell
ghc: 7.6
env:
  global:
    - PATH=$PATH:~/.local/bin
cache:
  directories:
    - $HOME/.pip-cache
install:
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py --user
  - pip install pytest hy --download-cache $HOME/.pip-cache --user
  - cd haskell && cabal install --only-dependencies && cd ..
  # command to run tests
script:
  - make -j 2 test
