sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
cache:
  directories:
  - $PWD/wheelhouse
env:
  global:
    - export PIP_FIND_LINKS=$PWD/wheelhouse
install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt
# command to run tests
script: py.test check.py check_hy.py
