sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
cache:
  directories:
  - $HOME/.pip-cache
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
# command to run tests
script: py.test check.py check_hy.py