language: haskell
ghc: 7.6
install:
  - sudo apt-get update && sudo apt-get install -y python-pip
  - sudo pip install pytest hy
  - cabal install base-unicode-symbols
  # command to run tests
script:
  - make -j 2 test
